from .data_elements import DATA_ELEMENTS


MANDATORY_FIELD_ORDER = [
    DATA_ELEMENTS["DBA"],
    DATA_ELEMENTS["DCS"],
    DATA_ELEMENTS["DAC"],
    DATA_ELEMENTS["DBD"],
    DATA_ELEMENTS["DBB"],
    DATA_ELEMENTS["DBC"],
    DATA_ELEMENTS["DAY"],
    DATA_ELEMENTS["DAQ"],
    DATA_ELEMENTS["DAK"],
]